[package]
name = "my-arc-swap-bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-swap = "1.5.0"
aligned = "0.4.0"
parking_lot = "0.12.0"

[profile.bench]
debug = 2
